from turtle import Turtle,Screen

timmy_the_turtle = Turtle()
timmy_the_turtle.shape("turtle")
timmy_the_turtle.color("green")
timmy_the_turtle.forward(200)
timmy_the_turtle.right(90)
timmy_the_turtle.forward(200)
timmy_the_turtle.right(90)
timmy_the_turtle.forward(200)
timmy_the_turtle.right(90)
timmy_the_turtle.forward(200)



tom_the_turtle = Turtle()
tom_the_turtle.shape("turtle")
tom_the_turtle.color("green")
tom_the_turtle.forward(200)
tom_the_turtle.left(90)
tom_the_turtle.forward(200)
tom_the_turtle.left(90)
tom_the_turtle.forward(200)
tom_the_turtle.left(90)
tom_the_turtle.forward(200)


jom_the_turtle = Turtle()
jom_the_turtle.shape("turtle")
jom_the_turtle.color("green")
jom_the_turtle.backward(200)
jom_the_turtle.left(90)
jom_the_turtle.backward(200)
jom_the_turtle.right(90)
jom_the_turtle.forward(200)
jom_the_turtle.left(90)
jom_the_turtle.forward(200)
jom_the_turtle.right(90)


tommy_the_turtle=Turtle()
tommy_the_turtle.shape("turtle")
tommy_the_turtle.color("green")
tommy_the_turtle.backward(200)
tommy_the_turtle.right(90)
tommy_the_turtle.backward(200)
tommy_the_turtle.left(90)
tommy_the_turtle.forward(200)
tommy_the_turtle.right(90)
tommy_the_turtle.forward(200)
tom_the_turtle.right(90)
"""
square=Turtle()
square.shape("arrow")
square.color("black")
square.forward(100)
square.left(90)
square.forward(100)
square.left(90)
square.forward(100)
square.left(90)
square.forward(100)
square.left(90)
"""
screen = Screen()
screen.exitonclick()